# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bs8rueR0gg6zRpszPOFwJBxJoi89ln5_
"""

# Student Performance Prediction

# 1. Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 2. Generate Dataset
np.random.seed(42)

data_size = 200

study_hours = np.random.randint(1, 10, data_size)
attendance = np.random.randint(50, 100, data_size)
previous_score = np.random.randint(40, 100, data_size)

# Pass = 1, Fail = 0
result = (study_hours * 2 + attendance * 0.3 + previous_score * 0.5 > 80).astype(int)

# Create DataFrame
df = pd.DataFrame({
    "Study_Hours": study_hours,
    "Attendance": attendance,
    "Previous_Score": previous_score,
    "Result": result
})

# 3. Data Exploration
print("Dataset Head:\n", df.head())
print("\nDataset Info:")
print(df.info())
print("\nClass Distribution:\n", df["Result"].value_counts())

# 4. Visualization
plt.figure(figsize=(6, 4))
plt.scatter(df["Study_Hours"], df["Previous_Score"], c=df["Result"])
plt.xlabel("Study Hours")
plt.ylabel("Previous Score")
plt.title("Student Performance Distribution")
plt.show()

# 5. Feature Selection
X = df[["Study_Hours", "Attendance", "Previous_Score"]]
y = df["Result"]

# 6. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 7. Model Training
model = LogisticRegression()
model.fit(X_train, y_train)

# 8. Prediction
y_pred = model.predict(X_test)

# 9. Evaluation
accuracy = accuracy_score(y_test, y_pred)
print("\nModel Accuracy:", accuracy)

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n", classification_report(y_test, y_pred))

# 10. User Input Prediction
print("\n--- Predict Student Result ---")
sh = int(input("Enter Study Hours per Day: "))
att = int(input("Enter Attendance Percentage: "))
ps = int(input("Enter Previous Exam Score: "))

prediction = model.predict([[sh, att, ps]])

if prediction[0] == 1:
    print("Prediction: Student will PASS ")
else:
    print("Prediction: Student may FAIL ")