# -*- coding: utf-8 -*-
"""Optimization.ipye

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trHn78aoiDgaevkVI_N30fRRMckaq4as
"""

import random  # Import random module to make random choices

# Define a Space where houses and hospitals are placed
class Space():

    def __init__(self, height, width, num_hospitals):
        """Initialize the space with dimensions and number of hospitals."""
        self.height = height                # Number of rows in the grid
        self.width = width                  # Number of columns in the grid
        self.num_hospitals = num_hospitals  # How many hospitals to place
        self.houses = set()                 # Set to store all house positions
        self.hospitals = set()              # Set to store all hospital positions

    def add_house(self, row, col):
        """Add a house at a given (row, col) coordinate."""
        self.houses.add((row, col))

    def available_spaces(self):
        """Return all empty spaces not occupied by houses or hospitals."""

        # Generate all possible grid coordinates
        candidates = set(
            (row, col)
            for row in range(self.height)
            for col in range(self.width)
        )

        # Remove spaces occupied by houses
        for house in self.houses:
            candidates.discard(house)

        # Remove spaces occupied by hospitals
        for hospital in self.hospitals:
            candidates.discard(hospital)

        return candidates  # Remaining free cells

    def hill_climb(self, maximum=None, image_prefix=None, log=False):
        """
        Perform hill-climbing optimization to place hospitals minimizing total cost.
        maximum: maximum number of iterations (optional)
        image_prefix: for saving images (optional)
        log: print progress if True
        """
        count = 0  # Counter for iterations

        # Step 1: Start with random hospital locations
        self.hospitals = set()

      #controls the logs
        for i in range(self.num_hospitals):
            self.hospitals.add(random.choice(list(self.available_spaces())))

        if log:
            print("Initial state: cost", self.get_cost(self.hospitals))

        if image_prefix:
            self.output_image(f"{image_prefix}{str(count).zfill(3)}.png")

        # Step 2: Improve the solution iteratively
        while maximum is None or count < maximum:
            count += 1
            best_neighbors = []          # List of best neighbor states
            best_neighbor_cost = None    # Cost of best neighbor

            # Try moving each hospital to all valid neighboring cells
            for hospital in self.hospitals:

                for replacement in self.get_neighbors(*hospital):

                    # Generate a neighbor state
                    neighbor = self.hospitals.copy()
                    neighbor.remove(hospital)
                    neighbor.add(replacement)

                    # Calculate the cost of the neighbor state
                    cost = self.get_cost(neighbor)

                    # If this neighbor is better, record it
                    if best_neighbor_cost is None or cost < best_neighbor_cost:
                        best_neighbor_cost = cost
                        best_neighbors = [neighbor]
                    elif best_neighbor_cost == cost:
                        best_neighbors.append(neighbor)

            # Step 3: If no better neighbor found, stop
            if best_neighbor_cost >= self.get_cost(self.hospitals):
                return self.hospitals

            # Step 4: Otherwise move to a random best neighbor
            else:
                if log:
                    print(f"Found better neighbor: cost {best_neighbor_cost}")
                self.hospitals = random.choice(best_neighbors)

            # Save image after each move (optional)
            if image_prefix:
                self.output_image(f"{image_prefix}{str(count).zfill(3)}.png")

    #this is varieation of hill-climbing algorithom
    def random_restart(self, maximum, image_prefix=None, log=False):
        """
        Perform hill-climbing multiple times to escape local optima.
        maximum: number of restart attempts
        """
        best_hospitals = None
        best_cost = None

        # Run multiple hill climbs
        for i in range(maximum):
            hospitals = self.hill_climb()
            cost = self.get_cost(hospitals)

            # Keep track of the best solution found so far
            if best_cost is None or cost < best_cost:
                best_cost = cost
                best_hospitals = hospitals
                if log:
                    print(f"{i}: Found new best state: cost {cost}")
            else:
                if log:
                    print(f"{i}: Found state: cost {cost}")

            # Save image after each attempt (optional)
            if image_prefix:
                self.output_image(f"{image_prefix}{str(i).zfill(3)}.png")

        return best_hospitals

    def get_cost(self, hospitals):
        """Calculate total Manhattan distance from each house to nearest hospital."""
        cost = 0

        # For every house, find distance to nearest hospital
        for house in self.houses:
            min_distance = min(
                abs(house[0] - hospital[0]) + abs(house[1] - hospital[1])
                for hospital in hospitals
            )
            cost += min_distance

        return cost

    def get_neighbors(self, row, col):
        """Return list of valid neighboring cells that are free."""
        candidates = [
            (row - 1, col),   # Up
            (row + 1, col),   # Down
            (row, col - 1),   # Left
            (row, col + 1)    # Right
        ]

        neighbors = []

        for r, c in candidates:
            # Skip if out of bounds or occupied
            if (r, c) in self.houses or (r, c) in self.hospitals:
                continue
            if 0 <= r < self.height and 0 <= c < self.width:
                neighbors.append((r, c))

        return neighbors

  #generating output here
    def output_image(self, filename):
        """Create and save an image showing the houses, hospitals, and cost."""
        from PIL import Image, ImageDraw, ImageFont

        cell_size = 100   # Size of each cell
        cell_border = 2   # Border around cells
        cost_size = 40    # Space for cost display
        padding = 10      # Padding around text

        # Create blank white canvas
        img = Image.new(
            "RGBA",
            (self.width * cell_size,
             self.height * cell_size + cost_size + padding * 2),
            "white"
        )

        # Load images for house and hospital
        house = Image.open("/content/House.png").resize((cell_size, cell_size))
        hospital = Image.open("/content/Hospital.png").resize((cell_size, cell_size))
        font = ImageFont.truetype("/content/OpenSans-Regular.ttf", 30)
        draw = ImageDraw.Draw(img)

        # Draw the grid
        for i in range(self.height):
            for j in range(self.width):

                # Draw black cell background
                rect = [
                    (j * cell_size + cell_border, i * cell_size + cell_border),
                    ((j + 1) * cell_size - cell_border, (i + 1) * cell_size - cell_border)
                ]
                draw.rectangle(rect, fill="black")

                # Paste house or hospital if present
                if (i, j) in self.houses:
                    img.paste(house, rect[0], house)
                if (i, j) in self.hospitals:
                    img.paste(hospital, rect[0], hospital)

        # Draw a black bar for cost at the bottom
        draw.rectangle(
            (0, self.height * cell_size, self.width * cell_size,
             self.height * cell_size + cost_size + padding * 2),
            "black"
        )

        # Write the cost text
        draw.text(
            (padding, self.height * cell_size + padding),
            f"Cost: {self.get_cost(self.hospitals)}",
            fill="white",
            font=font
        )

        # Save the final image
        img.save(filename)


# *******Main Execution******

# Create a new Space with 10 rows, 20 columns, and 3 hospitals
s = Space(height=10, width=20, num_hospitals=3)

# Randomly add 15 houses to the space
for i in range(15):
    s.add_house(random.randrange(s.height), random.randrange(s.width))

# Run hill-climbing search to find good hospital placements
hospitals = s.hill_climb(image_prefix="hospitals", log=True)
